Apriltag pose estimator
FRCTeam3255/Robot2023 pull request #25
Opened 2023-01-14 02:10 UTC by ACat701

Closes #5

2023-01-14 09:48 UTC, IanSzalai commented on src/main/java/frc/robot/subsystems/Vision.java
> +    PhotonCamera lifecam = new PhotonCamera("Microsoft_LifeCam_HD-3000");
either camera names or PhotonCamera objects should probably be in constants

2023-01-18 06:57 UTC, IanSzalai commented on src/main/java/frc/robot/subsystems/Vision.java
> +    Transform3d robotToAR = new Transform3d(new Translation3d(0, 0, 0), new Rotation3d(0, 0, 0));
should be a constant

2023-01-18 06:57 UTC, IanSzalai commented on src/main/java/frc/robot/subsystems/Vision.java
> +    Transform3d robotToOV = new Transform3d(new Translation3d(0, 0, 0), new Rotation3d(0, 0, 0));
also should be a constant

2023-01-23 22:50 UTC, IanSzalai commented
this is probably ready for review, @ACat701 you think so?

2023-01-23 22:58 UTC, ACat701 commented
> this is probably ready for review, @ACat701 you think so?

Yeah. If we want to change the pose estimation strategy in the future that can be a separate issue (but I don't think we're doing that anyway)

2023-01-25 03:59 UTC, AngelaKimmy submitted a review, later dismissed
Looks good to me. Nice and clean too! :)

2023-01-25 04:15 UTC, TaylerUva requested changes

2023-01-25 04:15 UTC, TaylerUva commented on src/main/java/frc/robot/Constants.java
> -  public static final boolean OUTPUT_DEBUG_VALUES = false;
This should be set back to false

2023-01-25 04:17 UTC, TaylerUva approved these changes

2023-01-25 04:18 UTC, merged