Added led control
FRCTeam3255/Robot2023 pull request #30
Opened 2023-01-14 19:03 UTC by KaneBarnes

Added the code for led control testing

2023-01-15 00:11 UTC, TaylerUva requested changes

2023-01-15 00:11 UTC, TaylerUva commented on src/main/java/frc/robot/RobotContainer.java
> +  private final SN_SwitchboardStick conSwitchboard = new SN_SwitchboardStick(2);
Updated pull from latest qa branch and add switchboard stick to robotMap

2023-01-16 19:35 UTC, AngelaKimmy approved these changes

2023-01-16 19:36 UTC, AngelaKimmy approved these changes

2023-01-16 19:38 UTC, merged